"""init tables

Revision ID: 586bbdb5b7dc
Revises: a6cb3047d9a3
Create Date: 2020-03-03 03:32:27.353045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '586bbdb5b7dc'
down_revision = 'a6cb3047d9a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ih_order_info', sa.Column('trade_no', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ih_order_info', 'trade_no')
    # ### end Alembic commands ###
